export interface CalendarAddUpdModel {
    BcProductId: number,
    CalendarName: string,
    CalendarTypeId: number,
    TimeAppointment: string,
    IsDeleted: boolean,
    IsActive: boolean,
    CalendarId: number,
    SuStartTime:string,
    SuEndTime:string,
    SuClosedDay:boolean,
    MoStartTime:string,
    MoEndTime:string,
    MoClosedDay:boolean,
    TuStartTime:string,
    TuEndTime:string,
    TuClosedDay:boolean,
    WeStartTime:string,
    WeEndTime:string,
    WeClosedDay:boolean,
    ThStartTime:string,
    ThEndTime:string,
    ThClosedDay:boolean,
    FrStartTime:string,
    FrEndTime:string,
    FrClosedDay:boolean,
    SaStartTime:string,
    SaEndTime:string,
    SaClosedDay:boolean,
  };